### ISSUE TITLE
utop, lambda-term and zed

### ISSUE THREAD

**Issue by diml** [ocaml-community/manifesto#5]
I'd like to propose the three following projects I wrote:

- https://github.com/diml/utop
- https://github.com/diml/lambda-term
- https://github.com/diml/zed

utop is a popular alternative to the OCaml toplevel. It provides nice features such as line edition and completion. The code hasn't changed much in a while, so it is stable and overall the project is low maintenance. However, as it uses the compiler-libs, it does often require small adjustments and a new opam release when a new version of the compiler is released.

lambda-term is a terminal library for OCaml. It is a dependency of utop and is used by a few projects in opam. As utop, the code hasn't changed in a while and is even lower maintenance. I believe that https://github.com/pqwy/notty is now a better alternative but utop and a few other projects are still using lambda-term.

zed is an *abstract edition engine*. It is a dependency of lambda-term and is used to implement line edition.

**Comment by pmetzger** [comment]
These seem good. I'll add you to the organization membership tomorrow and you can move the repositories over.

**Comment by diml** [comment]
Sounds good. I'm away this afternoon and tomorrow, so I'll probably do the transfer on Monday.

**Comment by pmetzger** [comment]
You should have an invite in your mailbox now.

**Comment by diml** [comment]
I found some time to do in today in the end. I've now transferred the repository. Happy for utop to be the first project to have joined ocaml-community :)

**Comment by pmetzger** [comment]
Thank you! Please update the `opam` files etc. to reflect the new location.

We may wish to create a team for each of the projects to add people with direct commit access to them. You should be able to do that given your permissions. If you do, try to make the team reflective of their purpose (maybe something like "utop-team", "zed-team", etc.), and we should document this procedure.

**Comment by diml** [comment]
OK, I'll update the opam files. Regarding commit rights, I'm happy to give write access to everyone in the organization.

For project assigments, I suggest to use the github [code owners](https://help.github.com/articles/about-codeowners/) feature. It feels like a lighter way to handle this and the right people will automatically get assigned as reviewers.

**Comment by pmetzger** [comment]
I didn't know about the CODEOWNERS feature, it looks rather neat!

If we have teams, I believe we can do things like adding collaborators on particular repositories who are not members of the organization. Probably worth exploring in the coming weeks.

**Comment by Drup** [comment]
@pmetzger You can already give rights on repositories in an organization to non-members through "external contributors".

**Comment by pmetzger** [comment]
Does that require that you add the external contributors to a team or do you just ACL them per repository?

**Comment by Drup** [comment]
The later.

**Comment by diml** [comment]
I updated the opam files and added codeowners files. @rgrinberg I added you as code owner of utop with me, let me know if don't want that.

What's left to do is setup the CI. I'm not sure how that works for organizations.

**Comment by rgrinberg** [comment]
It's fine with me.

**Comment by pmetzger** [comment]
> What's left to do is setup the CI. I'm not sure how that works for organizations.

For now I think we can just do a travis setup, unless you think there's a better way?

**Comment by diml** [comment]
But should we use personal travis accounts? Somehow it seems better to use an organization one.

**Comment by anuragsoni** [comment]
Anybody with the "Owner" role in the organization should be able to setup a travis build with the organization account

**Comment by pmetzger** [comment]
Okay, but what are the steps I need to undertake?

**Comment by anuragsoni** [comment]
If you login to travis you should be able to see the organizations where you are an admin/owner. I believe turning on the travis setup from there should be enough. Once you login to `travis.com` and click on your profile, you should see the `ocaml-community` organization there.

![screen shot 2018-08-21 at 1 08 05 pm](https://user-images.githubusercontent.com/5814535/44417406-6c1c8380-a543-11e8-807c-7ecaae7ea1fa.png)

**Comment by pmetzger** [comment]
I believe I've done the correct thing, but I'm not sure how to check? @diml?

**Comment by anuragsoni** [comment]
there should be an option to trigger a build on the Travis dashboard.

![screen shot 2018-08-21 at 3 31 05 pm](https://user-images.githubusercontent.com/5814535/44424536-5dd86280-a557-11e8-9496-ac27c650f47a.png)

**Comment by pmetzger** [comment]
I think I just triggered a build for utop. The status icon will need to have its URL updated.

**Comment by diml** [comment]
Thanks. I guess everything is now done for these repositories then?

**Comment by pmetzger** [comment]
Well, sort of. We should...

1. add a travis CI for `lambda-term` and `zed`
2. update the opam files for them to point at the current locations
3. add CODEOWNERS files (see https://help.github.com/articles/about-codeowners/ ) to the repos.

I think at that point we're done for the moment.

**Comment by anuragsoni** [comment]
`lambda-term` and `zed` already have codeowners file.

I made a pull request to zed earlier to switch to dune 1.0. I can make a separate PR for `zed` and `lambda-term` later today to add a travis config and updating the opam files, if nobody else gets to it before.

**Comment by anuragsoni** [comment]
I've made a pull request to add a travis config for zed, and a pull request to update `lambda-term` to use dune files and adding a travis config

**Comment by pmetzger** [comment]
Okay, is anything left here at this point, or can we close the issue, with the migration declared successful?

**Comment by diml** [comment]
I think we can close it and declare it successful :)

**Comment by diml** [comment]
Sure. You mean discuss.ocaml.org right?

**Comment by diml** [comment]
Done: https://discuss.ocaml.org/t/utop-has-successfully-moved-to-ocaml-comminuty/2459

**Comment by pmetzger** [comment]
discuss is built on software called discourse. :)
