### ISSUE TITLE
lwt_ssl, lwt_glib, lwt_log, lwt_camlp4

### ISSUE THREAD

**Issue by aantron** [ocaml-community/manifesto#6]
These were all factored out of Lwt recently (ocsigen/lwt#532. ocsigen/lwt#524, ocsigen/lwt#511, ocsigen/lwt#517).

I maintain them, and will be happy to continue doing so. Each package already has a working CI setup.

Almost no work is required on these, but sometimes something needs to be tweaked, especially when there are changes in major versions of Lwt.

**Comment by aantron** [comment]
Links:

- https://github.com/aantron/lwt_ssl
- https://github.com/aantron/lwt_glib
- https://github.com/aantron/lwt_camlp4
- https://github.com/aantron/lwt_log

**Comment by Drup** [comment]
No. Those should be either lwt or ocsigen, not discharged into a ocaml-community as a landfill.

**Comment by aantron** [comment]
Let's move them to ocsigen then.

From my point of view, moving these repos from my personal account to ocaml-community is a strict improvement, as more people will immediately get write access to maintain them.

**Comment by pmetzger** [comment]
@drup and @aantron, you guys decide on where to move them. I'm happy with them being moved to ocaml-community (which I hope is not landfill but rather an active place to maintain important code!), but failing that, I'd guess that the github ocsigen organization would be fine. (I'm correct that there's no separate lwt organization, correct? Perhaps there should be?)

**Comment by aantron** [comment]
We ended up transferring the repos to the ocsigen org.
